
NVCC        = nvcc
NVCC_FLAGS  = -O3 -I/usr/local/cuda/include
LD_FLAGS    = -lcudart -L/usr/local/cuda/lib64
EXE	        = convolution_CUDA
OBJ	        = convolution_CUDA.o support.o

default: $(EXE)

FILE = mat_input.csv

OUT = out.csv

run:
	clear
	make
	./$(EXE) 2048 2048 $(FILE) $(OUT) time.csv


convolution_CUDA.o: convolution_CUDA.cu kernel.cu support.h
	$(NVCC) -c -o $@ convolution_CUDA.cu $(NVCC_FLAGS)

support.o: support.cu support.h
	$(NVCC) -c -o $@ support.cu $(NVCC_FLAGS)

$(EXE): $(OBJ)
	$(NVCC) $(OBJ) -o $(EXE) $(LD_FLAGS)

clean:
	rm -rf *.o $(EXE)
